name: Seerr
version: 0.2.0
slug: overseerr
description: Media request and discovery manager for Jellyfin, Plex, and Emby
url: https://github.com/hassio-addons/app-seerr/tree/main/README.md
webui: http://[HOST]:[PORT:5055]
init: false
arch:
- aarch64
- amd64
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  5055/tcp: 5055
image: ghcr.io/hassio-addons/overseerr
