---
channel: stable
addons:
  aircast:
    repository: hassio-addons/addon-aircast
    target: aircast
    image: hassioaddons/aircast-{arch}
  airsonos:
    repository: hassio-addons/addon-airsonos
    target: airsonos
    image: hassioaddons/airsonos-{arch}
  appdaemon3:
    repository: hassio-addons/addon-appdaemon3
    target: appdaemon
    image: hassioaddons/appdaemon3-{arch}
  example:
    repository: hassio-addons/addon-example
    target: example
    image: hassioaddons/example-{arch}
  ftp:
    repository: hassio-addons/addon-ftp
    target: ftp
    image: hassioaddons/ftp-{arch}
  grafana:
    repository: hassio-addons/addon-grafana
    target: grafana
    image: hassioaddons/grafana-{arch}
  happy-bubbles:
    repository: hassio-addons/addon-happy-bubbles
    target: happy-bubbles
    image: hassioaddons/happy-bubbles-{arch}
  homebridge:
    repository: hassio-addons/addon-homebridge
    target: homebridge
    image: hassioaddons/homebridge-{arch}
  ide:
    repository: hassio-addons/addon-ide
    target: ide
    image: hassioaddons/ide-{arch}
  influxdb:
    repository: hassio-addons/addon-influxdb
    target: influxdb
    image: hassioaddons/influxdb-{arch}
  log-viewer:
    repository: hassio-addons/addon-log-viewer
    target: log-viewer
    image: hassioaddons/log-viewer
  lovelace-migration:
    repository: hassio-addons/addon-lovelace-migration
    target: lovelace-migration
    image: hassioaddons/lovelace-migration
  node-red:
    repository: hassio-addons/addon-node-red
    target: node-red
    image: hassioaddons/node-red-{arch}
  octobox:
    repository: hassio-addons/addon-octobox
    target: octobox
    image: hassioaddons/octobox
  pi-hole:
    repository: hassio-addons/addon-pi-hole
    target: pi-hole
    image: hassioaddons/pi-hole-{arch}
  plex:
    repository: hassio-addons/addon-plex
    target: plex
    image: hassioaddons/plex-{arch}
  shinobi:
    repository: hassio-addons/addon-shinobi
    target: shinobi
    image: hassioaddons/shinobi-{arch}
  spotify:
    repository: hassio-addons/addon-spotify-connect
    target: spotify
    image: hassioaddons/spotify
  tasmoadmin:
    repository: hassio-addons/addon-tasmoadmin
    target: tasmoadmin
    image: hassioaddons/sonweb-{arch}
  ssh:
    repository: hassio-addons/addon-ssh
    target: ssh
    image: hassioaddons/ssh-{arch}
  tor:
    repository: hassio-addons/addon-tor
    target: tor
    image: hassioaddons/tor-{arch}
  unifi:
    repository: hassio-addons/addon-unifi
    target: unifi
    image: hassioaddons/unifi

