---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/labels.yaml@e0c532a7b0fb264b3ff0c718c2c0308a0c8c1390 # v4.0.0
