---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/repository-lint.yaml@383c10d83acbe341acbb35a4a61bfd14827f00f0 # v3.0.0
