---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/repository-lint.yaml@e0c532a7b0fb264b3ff0c718c2c0308a0c8c1390 # v4.0.0
