---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@c953d10f34dac22eb68c1cdedbbc4106a89bef88 # v3.0.1
