---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@3846ae0fd09acec8ac1ac308ceacd052b9d01bec # v2.0.6
