---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/stale.yaml@c953d10f34dac22eb68c1cdedbbc4106a89bef88 # v3.0.1
